### PR TITLE
fix: use bankers rounding for decimal

### LINKED ISSUE #4: Round, half even
In DMN FEEL rounding is [_half-even_](https://en.wikipedia.org/wiki/Rounding#Round_half_to_even) not _up_ as it is in our current implementation.

```
round(1.5) = 2
round(2.5) = 2
```

### LINKED ISSUE #77: Decimal cast rounding behaves incorrectly
### Describe the Bug

When casting a number to decimal with a fixed set decimals, [several issues can be observed](https://nikku.github.io/feel-playground/?e=%7E3YCAkIBAgICAgICAgIC9AgCXnKkNRzxkGtTV3JcpokEWAkLQ6ZCJm6GmNrg7v3woGKNybfr3MVGrcRRKkIYbCY2apcsSKtoqFJVG8Ab02ZqY0%2Bkmo5tc%2BC4tNFz%2Ff17GwIA%3D&c=%7E3YCAkIC%2BgICAgICAgIC9AgCXnLILCNLEWVvD4A7RTE6e5VQHnL67RAf8ffGpOTFExGjxp2lIHt%2Fmy8diAzMQSsxIFwmdegBxI7oRrX98i6CA&t=expression&st=true).

- Negative numbers ALWAYS round up, even in extreme cases like `-5.5999999999 `-> `-5.5`
- Both negative and positive numbers round towards zero when it's ambiguous, which is the opposite behavior from zeebe, which favors rounding towards the nearest even `0.5` -> `0`, and `-1.5` -> `-2`, which is also what the DMN spec defines.

### Steps to Reproduce

See the [playground example](https://nikku.github.io/feel-playground/?e=%7E3YCAkIBAgICAgICAgIC9AgCXnKkNRzxkGtTV3JcpokEWAkLQ6ZCJm6GmNrg7v3woGKNybfr3MVGrcRRKkIYbCY2apcsSKtoqFJVG8Ab02ZqY0%2Bkmo5tc%2BC4tNFz%2Ff17GwIA%3D&c=%7E3YCAkIC%2BgICAgICAgIC9AgCXnLILCNLEWVvD4A7RTE6e5VQHnL67RAf8ffGpOTFExGjxp2lIHt%2Fmy8diAzMQSsxIFwmdegBxI7oRrX98i6CA&t=expression&st=true) for evaluations

### Expected Behavior

The rounding behavior should be consistent with the zeebe feel engine.

### PR DESCRIPTION
**Pull request by Skaiir**
### Which issue does this PR address?

Closes #77
Closes #4 (subset of 77)

### CODE REVIEW

**Comment by nikku** [comment]
Thanks for the PR. Does it make sense to address https://github.com/nikku/feelin/issues/4 in the process? Seems to be related.

**Comment by Skaiir** [comment]
Ah I didn't see the issue, it's actually the same so it would close both.

**Comment by Skaiir** [comment]
I can include changes to round as well :)

**Review by nikku — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
